name: Publish to Crates.io

on:
  release:
    types: [published]

jobs:
  # Call the external test workflow. 
  # This job must pass on all platforms defined in test.yml.
  run-tests:
    uses: ./.github/workflows/test.yml

  # The actual publish job
  publish:
    name: Publish Crate
    needs: [run-tests] # <--- Depends on the reusable workflow above
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to Crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token "${CARGO_REGISTRY_TOKEN}"
